stages:
  - pages

pages:
  stage: pages
  image: node:20
  script:
    - npm ci
    - npx gulp bundle
    - mkdir -p public/ui/${CI_COMMIT_TAG:-latest}
    - cp build/ui-bundle.zip public/ui/${CI_COMMIT_TAG:-latest}/ui-bundle.zip
  artifacts:
    paths:
      - public