stages:
  - pages

pages:
  stage: pages
  image: node:20
  script:
    - npm ci
    - npx gulp bundle
    - mkdir -p public/ui
    - cp build/ui-bundle.zip public/ui/ui-bundle.zip
  artifacts:
    paths:
      - public